import { Message } from "@/types";

const studentPhrases: Array<string> = [
  "can you explain",
  "help me understand",
  "show me how",
  "give solution",
  "give me solution",
  "guide me through",
  "step by step",
  "walk me through",
  "give example",
  "show example",
  "simple example",
  "code example",
  "demonstrate problem",
  "break it down",
  "explain detail",
  "check my work",
  "fix my code",
  "fix it",
  "full code",
  "working code",
  "correct code",
  "explain getline",
  "explain cout",
  "explain cin",
  "explain main",
  "explain return",
  "explain include",
  "explain namespace",
  "not sure",
  "i don't understand",
  "confused about",
  "what does this mean",
  "why does this happen",
  "can you clarify",
  "explain again",
  "not sure how",
  "how do i solve",
  "help me solve",
  "help me figure out",
  "i'm stuck",
  "stuck on this",
  "stuck on problem",
  "is this correct",
  "did i do this right",
  "check answer",
  "am i wrong",
  "validate solution",
  "confirm my work",
  "review this",
  "review my code",
  "review step",
  "for assignment",
  "for homework",
  "for exam",
  "need help",
  "need help question",
  "working on project",
  "practice problem",
  "study guide",
  "preparing for test",
  "help with topic",
  "explain concept",
  "what is c++",
  "what is variable",
  "what is function",
  "what is class",
  "what is object",
  "what is pointer",
  "what is reference",
  "what is array",
  "what is vector",
  "what is string",
  "what is loop",
  "what is for loop",
  "what is while loop",
  "what is if statement",
  "what is switch",
  "what is recursion",
  "how to print",
  "how to input",
  "how to read input",
  "how to use cout",
  "how to use cin",
  "how to use getline",
  "how to declare variable",
  "how to make function",
  "how to call function",
  "how to return value",
  "how to make array",
  "how to use vector",
  "how to use string",
  "how to use pointer",
  "why error",
  "why compiler error",
  "why segmentation fault",
  "why not working",
  "why wrong output",
  "why infinite loop",
  "why crash",
  "why fail",
  "logic help",
  "algorithm help",
  "solve this problem",
  "approach problem",
  "explain logic",
  "explain algorithm",
  "homework help",
  "assignment help",
  "project help",
  "lab help",
  "quiz question",
  "exam question",
  "what is pointer",
  "what is reference",
  "pointer vs reference",
  "pass by value",
  "pass by reference",
  "dynamic memory",
  "new operator",
  "delete operator",
  "memory leak",
  "what is constructor",
  "what is destructor",
  "what is inheritance",
  "what is polymorphism",
  "what is encapsulation",
  "what is template",
];

export function countTracker(messages: Message[]) {
  const phraseFrequency: Record<string, number> = {}; // reset every call

  messages.forEach((msg) => {
    const content = msg.content.toLowerCase();
    studentPhrases.forEach((phrase) => {
      if (content.includes(phrase)) {
        // count partial matches too
        phraseFrequency[phrase] = (phraseFrequency[phrase] || 0) + 1;
      }
    });
  });

  return phraseFrequency;
}
