import { Message } from "@/types";

const studentPhrases: Array<string> = [
  "can you explain",
  "help me understand",
  "show me how",
  "give solution",
  "give me solution",
  "guide me through",
  "step by step",
  "walk me through",
  "give example",
  "show example",
  "simple example",
  "code example",
  "demonstrate problem",
  "break it down",
  "explain detail",
  "check my work",
  "fix my code",
  "fix it",
  "full code",
  "working code",
  "correct code",
  "not sure",
  "i don't understand",
  "confused about",
  "what does this mean",
  "why does this happen",
  "can you clarify",
  "explain again",
  "not sure how",
  "how do i solve",
  "help me solve",
  "help me figure out",
  "i'm stuck",
  "stuck on this",
  "stuck on problem",
  "is this correct",
  "did i do this right",
  "check answer",
  "am i wrong",
  "validate solution",
  "confirm my work",
  "review this",
  "review my code",
  "review step",
  "for assignment",
  "for homework",
  "for exam",
  "need help",
  "need help question",
  "working on project",
  "practice problem",
  "study guide",
  "preparing for test",
  "help with topic",
  "explain concept",
  "what is c++",
  "what is variable",
  "what is function",
  "what is class",
  "what is object",
  "what is pointer",
  "what is reference",
  "what is array",
  "what is vector",
  "what is string",
  "what is loop",
  "what is for loop",
  "what is while loop",
  "what is if statement",
  "what is switch",
  "what is recursion",
  "how to print",
  "how to input",
  "how to read input",
  "how to use cout",
  "how to use cin",
  "how to use getline",
  "how to declare variable",
  "how to make function",
  "how to call function",
  "how to return value",
  "how to make array",
  "how to use vector",
  "how to use string",
  "how to use pointer",
  "why error",
  "why compiler error",
  "why segmentation fault",
  "why not working",
  "why wrong output",
  "why infinite loop",
  "why crash",
  "why fail",
  "logic help",
  "algorithm help",
  "solve this problem",
  "approach problem",
  "explain logic",
  "explain algorithm",
  "big o",
  "time complexity",
  "space complexity",
  "optimize code",
  "efficient algorithm",
  "sort algorithm",
  "search algorithm",
  "binary search",
  "linear search",
  "merge sort",
  "quick sort",
  "dynamic programming",
  "recursion problem",
  "stack usage",
  "queue usage",
  "linked list problem",
  "graph traversal",
  "depth first search",
  "breadth first search",
  "tree traversal",
  "hash table",
  "hash map",
  "collision handling",

  // OOP concepts
  "what is constructor",
  "what is destructor",
  "what is inheritance",
  "what is polymorphism",
  "what is encapsulation",
  "what is template",
  "virtual function",
  "abstract class",
  "interface usage",
  "overload function",
  "override method",
  "class design",
  "object interaction",
  "member function",
  "access specifier",
  "private member",
  "public member",
  "protected member",
  "pointer vs reference",
  "pass by value",
  "pass by reference",
  "dynamic memory",
  "new operator",
  "delete operator",
  "memory leak",
  "dangling pointer",
  "nullptr check",
  "address of variable",
  "dereference pointer",
  "segmentation fault",
  "compiler error",
  "runtime error",
  "logic error",
  "debug this",
  "why not compiling",
  "fix compilation",
  "fix runtime error",
  "check syntax",
  "code review",
  "homework help",
  "assignment help",
  "project help",
  "lab help",
  "quiz question",
  "exam question",
  "what is pointer",
  "what is reference",
  "need clarification",
  "how to start project",
  "check assignment",
  "validate output",
  "expected output",
  "test cases",
  "sample input",
  "sample output",
  "full program",
  "complete code",
  "function pointer",
  "lambda function",
  "standard library",
  "stl usage",
  "vector operations",
  "array operations",
  "string operations",
  "file input",
  "file output",
  "fstream usage",
  "ifstream",
  "ofstream",
  "cin.ignore",
  "getline usage",
  "command line arguments",
  "exception handling",
  "try catch",
  "throw exception",
  "debug output",
  "print variable",
  "track value",
  "loop logic",
  "conditional logic",
  "boolean expression",
  "operator precedence",
  "type casting",
  "static variable",
  "const keyword",
  "reference variable",
  "memory allocation",
  "object creation",
  "object destruction",
];
export function countTracker(messages: Message[]) {
  const phraseFrequency: Record<string, number> = {}; // reset every call
  messages.forEach((msg) => {
    const content = msg.content.toLowerCase().replace(/[^\w\s]/g, ""); // remove punctuation
    studentPhrases.forEach((phrase) => {
      if (content.includes(phrase.toLowerCase())) {
        const key = phrase.replace(/\b\w/g, (c) => c.toUpperCase());
        phraseFrequency[key] = (phraseFrequency[key] || 0) + 1;
      }
    });
  });
  return phraseFrequency;
}
